[workspace]
resolver = "2"
members = [
    "crates/benchmark",
    "crates/bicycle_isa",
    "crates/gross_code_cliffords",
    "crates/numerics",
    "crates/pbc_gross",
    "crates/random_numerics",
]

[workspace.package]
version = "0.0.1"
authors = [
    "Patrick Rall <patrickjrall@ibm.com>",
    "Eddie Schoute <eddie.schoute@ibm.com>",
    "John Lapeyre <john.lapeyre@ibm.com>",
]
description = "Bicycle architecture tools"
