[package]
name = "pbc_gross"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
bitcode = "0.6.5"
csv = "1.3.1"
env_logger = "0.11.6"
log = "0.4.26"
regex = "1.11.1"
serde = "1.0.218"
